"""
bootstrap/bootstrap_bootstrap_architecture.py

Creates the bootstrap package architecture used by future milestones.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BOOTSTRAP = ROOT / "bootstrap"

DIRS = [
    BOOTSTRAP / "common",
    BOOTSTRAP / "m03",
    BOOTSTRAP / "templates",
]

FILES = [
    BOOTSTRAP / "__init__.py",
    BOOTSTRAP / "common" / "__init__.py",
    BOOTSTRAP / "common" / "filesystem.py",
    BOOTSTRAP / "common" / "templates.py",
    BOOTSTRAP / "common" / "console.py",
    BOOTSTRAP / "common" / "verify.py",
    BOOTSTRAP / "common" / "summary.py",
    BOOTSTRAP / "m03" / "__init__.py",
    BOOTSTRAP / "m03" / "verify.py",
    BOOTSTRAP / "m03" / "database.py",
    BOOTSTRAP / "m03" / "lead.py",
    BOOTSTRAP / "m03" / "cli.py",
    BOOTSTRAP / "m03" / "tests.py",
    BOOTSTRAP / "m03" / "docs.py",
    BOOTSTRAP / "m03" / "summary.py",
]

CREATED = 0
SKIPPED = 0

HEADER = '"""Generated by BIP EOS Bootstrap Architecture."""\n\n'

def ensure_dir(path: Path):
    global CREATED
    if not path.exists():
        path.mkdir(parents=True, exist_ok=True)
        CREATED += 1
        print(f"[DIR ] {path}")

def ensure_file(path: Path):
    global CREATED, SKIPPED
    if path.exists():
        SKIPPED += 1
        print(f"[SKIP] {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    content = HEADER
    if path.name != "__init__.py":
        content += (
            "def run():\n"
            f'    print("{path.stem} ready.")\n'
        )
    path.write_text(content, encoding="utf-8")
    CREATED += 1
    print(f"[FILE] {path}")

def main():
    print("=" * 70)
    print("BIP EOS Bootstrap Architecture")
    print("=" * 70)
    for d in DIRS:
        ensure_dir(d)
    for f in FILES:
        ensure_file(f)
    print("-" * 70)
    print(f"Created : {CREATED}")
    print(f"Skipped : {SKIPPED}")
    print("Bootstrap architecture ready.")

if __name__ == "__main__":
    main()
