"""
bootstrap_bip_engineering_labs_architecture.py

Bootstraps the BIP Engineering Labs Architecture v1.0
repository structure.

Safe to run multiple times.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENGINEERING = ROOT / "engineering"

STRUCTURE = {
    "foundation": [
        "README.md",
        "FOUNDERS-LETTER.md",
        "CONSTITUTION.md",
        "FOUNDATIONAL-DOCUMENTS.md",
        "PA-001-bootstrap-intelligence-platform-architecture.md",
    ],
    "philosophy": [
        "README.md",
        "EP-001-engineering-philosophy.md",
        "EP-002-domain-first-engineering.md",
        "EP-003-architecture-before-implementation.md",
        "EP-004-engineering-as-a-product.md",
    ],
    "metamodel": [
        "README.md",
        "EM-001-engineering-specification.metamodel.yaml",
        "EM-002-domain-specification.metamodel.yaml",
        "EM-003-solution-architecture.metamodel.yaml",
        "EM-004-domain-lifecycle.metamodel.yaml",
        "EM-005-application.metamodel.yaml",
    ],
    "platform": [
        "README.md",
        "PA-001-bootstrap-intelligence-platform-architecture.md",
    ],
    "solutions": [
        "README.md",
        "SA-001-solution-architecture-standard.md",
        "SA-002-solution-lifecycle.md",
        "SA-003-solution-dependencies.md",
        "SA-004-solution-governance.md",
    ],
    "solutions/implementations/builder-intelligence": [],
    "solutions/implementations/academy": [],
    "solutions/implementations/ai-studio": [],
    "solutions/implementations/sales-intelligence": [],
    "solutions/implementations/future": [],
    "standards": [
        "README.md",
        "ES-001-engineering-specification-standard.md",
        "ES-002-documentation-standard.md",
        "ES-003-coding-standard.md",
        "ES-004-testing-standard.md",
    ],
    "domains": [
        "README.md",
        "DM-001-domain-specification-standard.md",
        "DM-002-domain-contract.md",
        "DM-003-domain-lifecycle.md",
        "DM-004-domain-validation.md",
    ],
    "adr": [],
    "governance": [],
    "reference": [],
    "milestones": [],
    "sprints": [],
}

HEADER = """# BIP Engineering Labs

Generated by the Bootstrap Intelligence Platform.

Status: Draft
"""

def touch(path: Path):
    if path.exists():
        print(f"[SKIP] {path}")
    else:
        path.write_text(HEADER, encoding="utf-8")
        print(f"[FILE] {path}")

def main():
    print("="*70)
    print("BIP Engineering Labs Architecture v1.0")
    print("="*70)
    ENGINEERING.mkdir(exist_ok=True)
    dirs=files=0
    for rel, filelist in STRUCTURE.items():
        d=ENGINEERING/rel
        if not d.exists():
            d.mkdir(parents=True, exist_ok=True)
            dirs+=1
            print(f"[DIR ] {d}")
        for f in filelist:
            touch(d/f)
            files+=1
    print("-"*70)
    print(f"Directories : {dirs}")
    print(f"Files       : {files}")
    print("="*70)
    print("Architecture ready.")

if __name__=="__main__":
    main()
