"""
bootstrap_compiler_architecture.py

Bootstraps the Engineering Compiler documentation structure.

Safe to run multiple times.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMPILER = ROOT / "engineering" / "compiler"

STRUCTURE = {
    "": ["README.md"],
    "specifications": [
        "EC-001-engineering-compiler-architecture.md",
        "ER-001-engineering-registry-specification.md",
        "EV-001-engineering-validation-engine.md",
        "DG-001-dependency-graph-specification.md",
        "MF-001-engineering-manifest-specification.md",
    ],
    "reference": ["README.md"],
    "diagrams": ["README.md"],
    "examples": ["README.md"],
}

HEADER = """# BIP Engineering Labs

Generated by the Bootstrap Intelligence Platform (BIP).

Status: Draft
"""

def ensure_dir(path):
    if path.exists():
        print(f"[SKIP] {path}")
    else:
        path.mkdir(parents=True, exist_ok=True)
        print(f"[DIR ] {path}")

def ensure_file(path):
    if path.exists():
        print(f"[SKIP] {path}")
    else:
        path.write_text(HEADER, encoding="utf-8")
        print(f"[FILE] {path}")

print("="*70)
print("BIP Engineering Compiler Architecture")
print("="*70)

ensure_dir(COMPILER)

dirs = 1
files = 0

for rel, items in STRUCTURE.items():
    d = COMPILER / rel if rel else COMPILER
    if rel:
        if not d.exists():
            d.mkdir(parents=True, exist_ok=True)
            print(f"[DIR ] {d}")
            dirs += 1
    for item in items:
        ensure_file(d / item)
        files += 1

print("-"*70)
print(f"Directories : {dirs}")
print(f"Files       : {files}")
print("="*70)
print("Engineering Compiler architecture ready.")
