"""
bootstrap_bfs002_demo.py

Demonstrates the UEOS BFS-002 Bootstrap Template Engine.
"""

from pathlib import Path

from bootstrap.engine.template_loader import TemplateLoader
from bootstrap.engine.template_parser import TemplateParser
from bootstrap.engine.variable_resolver import VariableResolver
from bootstrap.engine.renderer import TemplateRenderer
from bootstrap.engine.validator import TemplateValidator
from bootstrap.engine.writer import ArtifactWriter


def main():
    print("=" * 72)
    print("UEOS BFS-002 Demo")
    print("=" * 72)

    loader = TemplateLoader()
    parser = TemplateParser()
    resolver = VariableResolver()
    renderer = TemplateRenderer()
    validator = TemplateValidator()
    writer = ArtifactWriter()

    template_name = "markdown/readme.md.tpl"

    template_path = Path("bootstrap/templates") / template_name
    if not template_path.exists():
        template_path.parent.mkdir(parents=True, exist_ok=True)
        template_path.write_text(
            "# ${title}\n\nGenerated by ${author}\nVersion: ${version}\n",
            encoding="utf-8",
        )
        print(f"[CREATE ] {template_path}")

    template_text = loader.load(template_name)
    print(f"[LOAD   ] {template_name}")

    info = parser.parse(template_text)
    print(f"[PARSE  ] variables={info['variables']}")

    context = resolver.resolve(
        defaults={"author": "UEOS", "version": "1.0.0"},
        context={"title": "Bootstrap Framework System"},
    )

    output = renderer.render(template_text, context)

    issues = validator.validate_text(output)
    if issues:
        print("[ERROR  ] Validation failed")
        for issue in issues:
            print(" -", issue)
        return

    destination = "engineering/architecture/BFS-002/Generated-README.md"
    writer.write(destination, output)

    print(f"[WRITE  ] {destination}")
    print("=" * 72)
    print("BFS-002 pipeline executed successfully.")
    print("=" * 72)


if __name__ == "__main__":
    main()
