"""
bootstrap_eks_v4.py

BIP Engineering Labs
Engineering Knowledge System Bootstrap v4.0

Engineering-first architecture:
Meta-Models -> Specifications -> Implementations

Safe to run multiple times.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EKS = ROOT / "engineering"

TREE = {
    "foundation": [
        "README.md",
        "FOUNDERS-LETTER.md",
        "CONSTITUTION.md",
        "FOUNDATIONAL-DOCUMENTS.md",
    ],
    "philosophy": [
        "README.md",
        "EP-001-engineering-philosophy.md",
        "EP-002-domain-first-engineering.md",
        "EP-003-architecture-before-implementation.md",
        "EP-004-engineering-as-a-product.md",
    ],
    "metamodel": [
        "README.md",
        "EM-001-engineering-specification.metamodel.yaml",
        "EM-002-domain-specification.metamodel.yaml",
        "EM-003-solution-architecture.metamodel.yaml",
        "EM-004-domain-lifecycle.metamodel.yaml",
        "EM-005-application.metamodel.yaml",
        "EM-006-component.metamodel.yaml",
        "EM-007-event.metamodel.yaml",
        "EM-008-api.metamodel.yaml",
        "EM-009-permission.metamodel.yaml",
        "EM-010-report.metamodel.yaml",
    ],
    "platforms/specifications": [
        "PA-001-bootstrap-intelligence-platform-architecture.md",
        "PA-002-engineering-operating-system.md",
        "PA-003-engineering-knowledge-system.md",
        "PA-004-bootstrap-engine.md",
        "PA-005-application-framework.md",
    ],
    "solutions/specifications": [
        "SA-001-solution-architecture-standard.md",
        "SA-002-solution-lifecycle.md",
        "SA-003-solution-governance.md",
        "SA-004-solution-dependencies.md",
    ],
    "solutions/implementations/builder-intelligence": [],
    "solutions/implementations/academy": [],
    "solutions/implementations/ai-studio": [],
    "solutions/implementations/sales-intelligence": [],
    "solutions/implementations/future": [],
    "domains/specifications": [
        "DM-001-domain-specification-standard.md",
        "DM-002-domain-contract.md",
        "DM-003-domain-lifecycle.md",
        "DM-004-domain-validation.md",
        "DM-005-domain-events.md",
        "DM-006-domain-permissions.md",
        "DM-007-domain-api.md",
        "DM-008-domain-reports.md",
        "DM-009-domain-indexes.md",
        "DM-010-domain-testing.md",
    ],
    "standards": [
        "README.md",
        "ES-001-engineering-specification-standard.md",
        "ES-002-documentation-standard.md",
        "ES-003-coding-standard.md",
        "ES-004-testing-standard.md",
        "ES-005-api-standard.md",
        "ES-006-security-standard.md",
        "ES-007-versioning-standard.md",
    ],
    "governance": [],
    "adr": [],
    "reference": [],
    "milestones": [],
    "sprints": [],
}

MANIFEST = """version: 4.0.0

architecture:
  principle: "Knowledge -> Specification -> Implementation"

layers:
  - foundation
  - philosophy
  - metamodel
  - platforms
  - solutions
  - domains
  - standards
  - governance
  - adr
  - reference
  - milestones
  - sprints

pattern:
  metamodels: engineering language
  specifications: engineering contracts
  implementations: realizations
"""

HEADER = "# BIP Engineering Labs\n\nGenerated by Bootstrap Intelligence Platform.\n"

def ensure_dir(d):
    if d.exists():
        print(f"[SKIP] {d}")
    else:
        d.mkdir(parents=True, exist_ok=True)
        print(f"[DIR ] {d}")

def ensure_file(f, content=HEADER):
    if f.exists():
        print(f"[SKIP] {f}")
    else:
        f.write_text(content, encoding="utf-8")
        print(f"[FILE] {f}")

print("="*70)
print("BIP Engineering Labs Engineering Knowledge System v4.0")
print("="*70)

ensure_dir(EKS)

for rel, files in TREE.items():
    d = EKS / rel
    ensure_dir(d)
    readme = d / "README.md"
    if not readme.exists() and files:
        ensure_file(readme)
    for file in files:
        ensure_file(d / file)

ensure_file(EKS / "engineering.manifest.yaml", MANIFEST)

print("-"*70)
print("Knowledge → Specification → Implementation")
print("Engineering Knowledge System v4.0 ready.")
