#!/usr/bin/env python3
"""
bootstrap_cli_commands_v1.py
Creates the UEOS CLI command layout.
"""

from pathlib import Path

TREE = {
    "framework": ["__init__.py","command.py","parser.py","dispatcher.py","registry.py","help.py","output.py","errors.py"],
    "audit": ["__init__.py","commands.py","discover.py","analyze.py","validate.py","report.py"],
    "registry": ["__init__.py","commands.py","import_.py","export.py","verify.py","status.py"],
    "graph": ["__init__.py","commands.py","build.py","query.py","validate.py","visualize.py"],
    "compiler": ["__init__.py","commands.py","compile.py","emit.py","verify.py","package.py"],
    "publish": ["__init__.py","commands.py","documentation.py","reports.py","academy.py","website.py"],
    "knowledge": ["__init__.py","commands.py","ingest.py","search.py","classify.py","learn.py"],
    "academy": ["__init__.py","commands.py","curriculum.py","labs.py","exams.py","certifications.py"],
    "runtime": ["__init__.py","commands.py","doctor.py","health.py","plugins.py","services.py"],
}

HEADER = "\"\"\"\nUEOS CLI Module\nGenerated by Bootstrap Framework System (BFS)\n\"\"\"\n"

ROUTER = """\"\"\"
UEOS Constitutional Router
\"\"\"

def main():
    print("UEOS Constitutional CLI")
    print("Use: ueos <system> <command>")

if __name__ == "__main__":
    main()
"""

def write(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        print(f"[EXISTS ] {path}")
    else:
        path.write_text(text, encoding="utf-8")
        print(f"[CREATE ] {path}")

def main():
    root = Path.cwd() / "src" / "bip_eos" / "cli"
    root.mkdir(parents=True, exist_ok=True)

    write(root / "__init__.py", "\"\"\"UEOS CLI\"\"\"\n")
    write(root / "ueos.py", ROUTER)

    for subsystem, files in TREE.items():
        folder = root / subsystem
        for filename in files:
            if filename == "__init__.py":
                text = f"\"\"\"{subsystem.title()} CLI Package\"\"\"\n"
            elif filename == "commands.py":
                text = HEADER + f"# {subsystem.title()} command registry\n"
            else:
                text = HEADER + f"# {filename}\n"
            write(folder / filename, text)

    print("=" * 72)
    print("UEOS CLI command framework complete.")
    print("=" * 72)

if __name__ == "__main__":
    main()
