"""
bootstrap_eks_v2.py

BIP Engineering Labs
Engineering Knowledge System Bootstrap v2.0

Creates the Engineering Knowledge System (EKS) directory
structure using the adopted scalable architecture.

Safe to run multiple times.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENGINEERING = ROOT / "engineering"

STRUCTURE = {
    "foundation": [
        "README.md",
        "FOUNDERS-LETTER.md",
        "CONSTITUTION.md",
        "FOUNDATIONAL-DOCUMENTS.md",
        "PA-001-bootstrap-intelligence-platform-architecture.md",
    ],
    "philosophy": [
        "README.md",
        "EP-001-engineering-philosophy.md",
        "EP-002-domain-first-engineering.md",
        "EP-003-architecture-before-implementation.md",
        "EP-004-engineering-as-a-product.md",
    ],
    "metamodel": [
        "README.md",
        "EM-001-engineering-specification.metamodel.yaml",
        "EM-002-domain-specification.metamodel.yaml",
        "EM-003-solution-architecture.metamodel.yaml",
        "EM-004-domain-lifecycle.metamodel.yaml",
        "EM-005-application.metamodel.yaml",
        "EM-006-component.metamodel.yaml",
        "EM-007-event.metamodel.yaml",
        "EM-008-api.metamodel.yaml",
        "EM-009-permission.metamodel.yaml",
        "EM-010-report.metamodel.yaml",
    ],
    "platform": [
        "README.md",
        "PA-001-bootstrap-intelligence-platform-architecture.md",
        "PA-002-engineering-operating-system.md",
        "PA-003-engineering-knowledge-system.md",
        "PA-004-bootstrap-engine.md",
        "PA-005-application-framework.md",
    ],
    "solution": [
        "README.md",
        "SA-001-solution-architecture-standard.md",
        "SA-002-solution-lifecycle.md",
        "SA-003-solution-governance.md",
        "SA-004-solution-dependencies.md",
    ],
    "solution/implementations/builder-intelligence": [],
    "solution/implementations/academy": [],
    "solution/implementations/ai-studio": [],
    "solution/implementations/sales-intelligence": [],
    "solution/implementations/future": [],
    "domain": [
        "README.md",
        "DM-001-domain-specification-standard.md",
        "DM-002-domain-contract.md",
        "DM-003-domain-lifecycle.md",
        "DM-004-domain-validation.md",
        "DM-005-domain-events.md",
        "DM-006-domain-permissions.md",
        "DM-007-domain-api.md",
        "DM-008-domain-reports.md",
        "DM-009-domain-indexes.md",
        "DM-010-domain-testing.md",
    ],
    "standards": [
        "README.md",
        "ES-001-engineering-specification-standard.md",
        "ES-002-documentation-standard.md",
        "ES-003-coding-standard.md",
        "ES-004-testing-standard.md",
        "ES-005-api-standard.md",
        "ES-006-security-standard.md",
        "ES-007-versioning-standard.md",
    ],
    "adr": [],
    "governance": [],
    "reference": [],
    "milestones": [],
    "sprints": [],
}

HEADER = """# BIP Engineering Labs

Generated by the Bootstrap Intelligence Platform (BIP).

Status: Draft
"""

def ensure_dir(path):
    if path.exists():
        print(f"[SKIP] {path}")
    else:
        path.mkdir(parents=True, exist_ok=True)
        print(f"[DIR ] {path}")

def ensure_file(path):
    if path.exists():
        print(f"[SKIP] {path}")
    else:
        path.write_text(HEADER, encoding="utf-8")
        print(f"[FILE] {path}")

print("="*70)
print("BIP Engineering Labs Engineering Knowledge System v2.0")
print("="*70)

ENGINEERING.mkdir(exist_ok=True)

dirs = files = 0

for rel, items in STRUCTURE.items():
    d = ENGINEERING / rel
    if not d.exists():
        d.mkdir(parents=True, exist_ok=True)
        print(f"[DIR ] {d}")
        dirs += 1
    for item in items:
        ensure_file(d / item)
        files += 1

print("-"*70)
print(f"Directories : {dirs}")
print(f"Files       : {files}")
print("="*70)
print("Engineering Knowledge System ready.")
