#!/usr/bin/env python3
"""
bootstrap_cli_commands_v1.py
Creates the UEOS CLI command layout.
"""

from pathlib import Path

TREE = {
    "framework": ["__init__.py","command.py","parser.py","dispatcher.py","registry.py","help.py","output.py","errors.py"],
    "audit": ["__init__.py","commands.py","discover.py","analyze.py","validate.py","report.py"],
    "registry": ["__init__.py","commands.py","import_.py","export.py","verify.py","status.py"],
    "graph": ["__init__.py","commands.py","build.py","query.py","validate.py","visualize.py"],
    "compiler": ["__init__.py","commands.py","compile.py","emit.py","verify.py","package.py"],
    "publish": ["__init__.py","commands.py","documentation.py","reports.py","academy.py","website.py"],
    "knowledge": ["__init__.py","commands.py","ingest.py","search.py","classify.py","learn.py"],
    "academy": ["__init__.py","commands.py","curriculum.py","labs.py","exams.py","certifications.py"],
    "runtime": ["__init__.py","commands.py","doctor.py","health.py","plugins.py","services.py"],
}

HEADER = 
UEOS CLI Module
Generated by Bootstrap Framework System (BFS)
