"""
create_plugin.py

Bootstrap Plugin Generator

Usage:
    python create_plugin.py discovery
"""

from pathlib import Path
import sys

if len(sys.argv) != 2:
    print("Usage: python create_plugin.py <plugin_name>")
    raise SystemExit(1)

plugin = sys.argv[1].strip().lower()

root = Path("bootstrap") / "plugins" / plugin
tests = root / "tests"

root.mkdir(parents=True, exist_ok=True)
tests.mkdir(parents=True, exist_ok=True)

files = {
    "__init__.py": f'"""Bootstrap {plugin.title()} Plugin"""\n',
    "plugin.py": f'"""Main {plugin.title()} plugin."""\n',
    "crawler.py": f'"""Crawler for {plugin}."""\n',
    "extractor.py": f'"""AI extraction for {plugin}."""\n',
    "validator.py": f'"""Validation for {plugin}."""\n',
    "repository.py": f'"""Repository layer for {plugin}."""\n',
    "scheduler.py": f'"""Scheduler for {plugin}."""\n',
    "configuration.py": f'"""Configuration for {plugin}."""\n',
    "models.py": f'"""Models for {plugin}."""\n',
    "README.md": f"# {plugin.title()} Plugin\n\nGenerated by Bootstrap Engineering Factory.\n",
}

for name, content in files.items():
    path = root / name
    if not path.exists():
        path.write_text(content, encoding="utf-8")

(tests / "__init__.py").write_text("", encoding="utf-8")
(tests / "test_plugin.py").write_text(
    f'"""Tests for {plugin} plugin."""\n',
    encoding="utf-8",
)

print()
print("===================================")
print(" Bootstrap Plugin Generated")
print("===================================")
print(root.resolve())
