"""
============================================================
 BIP EOS Milestone 0002
 The Academy
============================================================
"""

from pathlib import Path

ROOT = Path("engineering") / "milestones"
MILESTONE = ROOT / "MILESTONE-0002.md"

CONTENT = """# BIP EOS Milestone 0002

## THE ACADEMY

### Mission

The Academy exists to preserve engineering culture.

It is the institutional memory of BIP EOS.

Every engineering decision...
Every lesson learned...
Every architecture pattern...
Every successful implementation...
Every mistake...
Every innovation...

becomes permanent knowledge.

Nothing valuable is forgotten.

---

## The Academy transforms

Experience

↓

Knowledge

↓

Curriculum

↓

Capability

↓

Engineering Excellence

---

## Every AI Agent

begins here.

Every Engineer contributes here.

Every Product improves here.

---

## First Law

Engineering knowledge must never be lost.

---

## Founding Principle

Build once.

Teach forever.

---

## Mission

☑ Build the Academy

☑ Train BIP EOS

☑ Preserve Engineering Knowledge

☑ Build the Future

☑ Do Some Damage

---

Generated by BIP EOS
"""

def banner():
    print("=" * 60)
    print(" BIP EOS Milestone Generator")
    print("=" * 60)

def create():
    ROOT.mkdir(parents=True, exist_ok=True)
    if MILESTONE.exists():
        print(f"• Exists   {MILESTONE}")
        return
    MILESTONE.write_text(CONTENT, encoding="utf-8")
    print(f"✓ Created {MILESTONE}")

def summary():
    print("-" * 60)
    print("Milestone 0002 complete.")
    print("The Academy has officially been founded.")
    print("=" * 60)

def main():
    banner()
    create()
    summary()

if __name__ == "__main__":
    main()
