#!/usr/bin/env python3
"""
bootstrap_engineering_foundation_v1.py

UEOS Bootstrap Program
Engineering Foundation v1.0

Purpose
-------
Creates the canonical engineering/ foundation for the
BIP Universal Engineering Operating System (UEOS).

Characteristics
---------------
- Python Standard Library only
- Safe by default
- Never overwrites existing files
"""

from pathlib import Path

STRUCTURE = {
    "constitution": [
        "mission",
        "laws",
        "constitutional_objects",
        "principles",
        "runtime",
        "methodology",
    ],
    "standards": [
        "coding",
        "documentation",
        "architecture",
        "testing",
        "bootstrap",
        "registry",
        "graph",
        "publishing",
        "security",
    ],
    "metamodel": [
        "objects",
        "relationships",
        "lifecycle",
        "schemas",
        "taxonomy",
        "ontology",
        "validation",
    ],
    "architecture": [
        "EA-001",
        "decisions",
        "diagrams",
        "models",
        "views",
        "history",
    ],
    "governance": [
        "policies",
        "compliance",
        "audits",
        "approvals",
        "reviews",
        "change_management",
    ],
    "specifications": [
        "runtime",
        "registry",
        "graph",
        "publishing",
        "academy",
        "api",
        "schemas",
    ],
    "knowledge": [
        "patterns",
        "research",
        "lessons_learned",
        "best_practices",
        "glossary",
        "references",
        "whitepapers",
    ],
}

README = """# {title}

## Constitutional Purpose

This directory is part of the UEOS Engineering Foundation.

Generated by:
bootstrap_engineering_foundation_v1.py
"""

def find_root(start: Path) -> Path:
    cur = start.resolve()
    while cur != cur.parent:
        if (cur / "src").exists() and (cur / "engineering").exists():
            return cur
        cur = cur.parent
    raise RuntimeError("Unable to locate UEOS repository root.")

def write_if_missing(path: Path, text: str):
    if path.exists():
        print(f"[EXISTS ] {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"[CREATE ] {path}")

def main():
    root = find_root(Path(__file__).parent)
    eng = root / "engineering"
    eng.mkdir(exist_ok=True)

    print("="*72)
    print("UEOS Engineering Foundation Bootstrap v1.0")
    print("="*72)

    for section, children in STRUCTURE.items():
        section_dir = eng / section
        section_dir.mkdir(parents=True, exist_ok=True)
        write_if_missing(
            section_dir / "README.md",
            README.format(title=section.replace("_"," ").title())
        )
        for child in children:
            d = section_dir / child
            d.mkdir(parents=True, exist_ok=True)
            write_if_missing(
                d / ".gitkeep",
                ""
            )

    manifest = eng / "manifest.yaml"
    if not manifest.exists():
        lines = [
            'constitution: "UEOS Engineering Foundation"',
            'version: "1.0.0"',
            "",
            "sections:"
        ]
        for s in STRUCTURE:
            lines.append(f"  - {s}")
        manifest.write_text("\n".join(lines)+"\n", encoding="utf-8")
        print(f"[CREATE ] {manifest}")
    else:
        print(f"[EXISTS ] {manifest}")

    print("="*72)
    print("Engineering Foundation complete.")
    print("Existing files were preserved.")
    print("="*72)

if __name__ == "__main__":
    main()
