#!/usr/bin/env python3
"""
bootstrap_runtime_architecture_v2.py

Creates the official UEOS Runtime Architecture v2.

Safe by default:
- Standard Library only
- Never overwrites existing files
- Creates only missing directories/files
"""

from pathlib import Path

RUNTIME = [
    "lifecycle",
    "scheduler",
    "event_bus",
    "dependency_injection",
    "configuration",
    "health",
    "telemetry",
    "diagnostics",
    "security",
    "plugins",
    "version",
]

SERVICES = [
    "logging",
    "documentation",
    "repository",
]

COMMON = [
    "exceptions",
    "interfaces",
    "identifiers",
    "types",
    "utilities",
]

README = """# {title}

Generated by bootstrap_runtime_architecture_v2.py

Constitutional Purpose
----------------------
Placeholder package created by the UEOS bootstrap.
"""

def find_root(start: Path) -> Path:
    cur = start.resolve()
    while cur != cur.parent:
        if (cur / "src").exists() and (cur / "engineering").exists():
            return cur
        cur = cur.parent
    raise RuntimeError("UEOS repository root not found.")

def create(path: Path):
    path.mkdir(parents=True, exist_ok=True)
    keep = path / ".gitkeep"
    if not keep.exists():
        keep.write_text("", encoding="utf-8")
        print(f"[CREATE ] {keep.relative_to(ROOT)}")

def readme(path: Path, title: str):
    f = path / "README.md"
    if not f.exists():
        f.write_text(README.format(title=title), encoding="utf-8")
        print(f"[CREATE ] {f.relative_to(ROOT)}")

ROOT = None

def main():
    global ROOT
    ROOT = find_root(Path(__file__).parent)

    base = ROOT / "src" / "bip_eos"

    runtime = base / "runtime"
    services = base / "services"
    storage = base / "storage"
    common = base / "common"

    for root_dir, items in (
        (runtime, RUNTIME),
        (services, SERVICES),
        (common, COMMON),
    ):
        root_dir.mkdir(parents=True, exist_ok=True)
        readme(root_dir, root_dir.name.title())
        for item in items:
            d = root_dir / item
            create(d)
            readme(d, item.replace("_", " ").title())

    storage.mkdir(parents=True, exist_ok=True)
    readme(storage, "Storage")

    for name in (
        "relational",
        "graph",
        "object",
        "filesystem",
        "repository",
        "cache",
    ):
        d = storage / name
        create(d)
        readme(d, name.title())

    print("=" * 72)
    print("UEOS Runtime Architecture v2 scaffold complete.")
    print("Existing files preserved.")
    print("=" * 72)

if __name__ == "__main__":
    main()
