from pathlib import Path
PROJECT_ROOT=Path(__file__).resolve().parents[3]
SRC_DIR=PROJECT_ROOT/"src"
DOCS_DIR=PROJECT_ROOT/"docs"
LOGS_DIR=PROJECT_ROOT/"logs"
REPORTS_DIR=PROJECT_ROOT/"reports"
REGISTRY_DIR=PROJECT_ROOT/"registry"
PLUGINS_DIR=PROJECT_ROOT/"plugins"
ENGINEERING_DIR=PROJECT_ROOT/"engineering"
BOOTSTRAP_DIR=PROJECT_ROOT/"bootstrap"
TEMPLATES_DIR=PROJECT_ROOT/"templates"
TESTS_DIR=PROJECT_ROOT/"tests"
